### ISSUE TITLE
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

### ISSUE THREAD

**Issue by godeye** [phistrom/mesh2img#1]
blender -b -P mesh2img.py -- --paths cube.stl --dimen                                                                                                                                                             sions 200 -i jpg
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
Traceback (most recent call last):
  File "/srv/mesh2img/mesh2img.py", line 485, in <module>
    Mesh2Img(**cliargs).start()  # pass in all the paths given on the command li                                                                                                                                                             ne
  File "/srv/mesh2img/mesh2img.py", line 84, in __init__
    self.materials = [mat_name.strip() for mat_name in material.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'

Blender quit

what this mean?

**Comment by phistrom** [comment]
Hi, @godeye 

If you go to [Line 60](https://github.com/phistrom/mesh2img/blob/1f557693189e45970d5a01ed2cdb3032244429a2/mesh2img.py#L60) and replace that ``None`` with two quotation marks back-to-back `""` does that fix it?

Change it from
`def __init__(self, paths=None, dimensions=None, material=None, image_format=None, verbose=False,` ...
To
`def __init__(self, paths=None, dimensions=None, material="", image_format=None, verbose=False,` ...

If you could confirm that fixes it, I will make the changes to this repo.

Thanks!

**Comment by cjhyy7190** [comment]
hello , I change the script as above. But it also has the same mistake.

**Comment by wine3603** [comment]
same error
