### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by ayennam** [phistrom/mesh2img#3]
cadtoimg/mesh2img$ blender -b -P mesh2img.py -- --paths /home/cadtoimg/bunny/data/bun180.ply --dimensions 200

Blender 2.90.1
Read prefs: /home/.config/blender/2.90/config/userpref.blend
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Traceback (most recent call last):
  File "/home/cadtoimg/mesh2img/mesh2img.py", line 485, in <module>
    Mesh2Img(**cliargs).start()  # pass in all the paths given on the command line
  File "/home/cadtoimg/mesh2img/mesh2img.py", line 84, in __init__
    self.materials = [mat_name.strip() for mat_name in material.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by anycam** [comment]
Did you find any solution for the problem?

**Comment by Hamza442004** [comment]
Blender has changed since this package was written so you should update it before using it.

**Comment by duswie** [comment]
add "-m Material" argument: 
blender -b -P mesh2img.py -- --paths /home/cadtoimg/bunny/data/bun180.ply --dimensions 20 -m Material

**Comment by ByteDrummer** [comment]
> add "-m Material" argument:
> blender -b -P mesh2img.py -- --paths /home/cadtoimg/bunny/data/bun180.ply --dimensions 20 -m Material

This doesn't seem to get rid of the problem for me. I now get:
```Blender 2.91.0 (hash 0f45cab862b8 built 2020-11-25 08:51:08)
found bundled python: /snap/blender/51/2.91/python
Traceback (most recent call last):
  File "mesh2img.py", line 485, in <module>
    Mesh2Img(**cliargs).start()  # pass in all the paths given on the command line
  File "mesh2img.py", line 152, in start
    delete_object_by_name("Cube", ignore_errors=True)  # factory default Blender has a cube in the default scene
  File "/mesh2img.py", line 430, in delete_object_by_name
    obj.select = True
AttributeError: 'Object' object has no attribute 'select'

Blender quit
```

**Comment by ByteDrummer** [comment]
@Hamza442004 I'm using your fork, and it seems to be working. It would help if you made a pull request.

**Comment by phistrom** [comment]
@ByteDrummer Merged.
